apiVersion: v1
kind: Pod
metadata:
  name: mit-fl-ta2
  labels:
    role: ta2
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: registry.datadrivendiscovery.org/jkanter/mit-fl-ta2:ci
    imagePullPolicy: IfNotPresent
    ports:
    - name: grpc
      containerPort: 45042
    env:
    - name: D3MCPU
      valueFrom:
        resourceFieldRef:
          containerName: main
          resource: limits.cpu
    - name: D3MRAM
      valueFrom:
        resourceFieldRef:
          containerName: main
          resource: limits.memory
    volumeMounts:
    - name: shared-memory
      mountPath: /dev/shm
      readOnly: false
    resources:
      limits:
        cpu: 3
        memory: 6Gi
  imagePullSecrets:
  - name: regcred
  volumes:
  - name: shared-memory
    emptyDir:
      medium: Memory
